# -*- coding: utf-8 -*-
"""generate_password in Python..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZgnebfVI0DjM2mXVcrCESP8dLnpNOCt
"""

import random
import string

def generate_password(length=12, include_digits=True, include_special_chars=True):
    # Define character sets
    lowercase_letters = string.ascii_lowercase
    uppercase_letters = string.ascii_uppercase
    digits = string.digits if include_digits else ''
    special_chars = string.punctuation if include_special_chars else ''

    # Combine character sets
    all_chars = lowercase_letters + uppercase_letters + digits + special_chars

    # Ensure the password length is at least 8 characters
    length = max(length, 8)

    # Generate password
    password = ''.join(random.choice(all_chars) for _ in range(length))

    return password


# Example usage
password = generate_password()
print("generate a random password")
print("------------------")

print("Generated Password:", password)