# -*- coding: utf-8 -*-
"""rock, paper, scissors game using Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SHlY3_-39CzNW3g7M1Sz01TS31OQ1edc
"""

import random

options = ['Rock', 'Paper', 'Scissors']

userOption = int(input('Press 1 for Rock, 2 for Paper, 3 for Scissors: \n'))
userChoice = options[userOption-1]

computerChoice = options[random.randint(0,2)]

print(f'You chose: {userChoice}')
print(f'Computer chose: {computerChoice}')

result = "It's a tie!"

if userChoice == "Rock":
    if computerChoice == "Paper":
        result = "Computer Won!"
    elif computerChoice == "Scissors":
        result = "You Won!"

elif userChoice == "Paper":
    if computerChoice == "Scissors":
        result = "Computer Won!"
    elif computerChoice == "Rock":
        result = "You Won!"

elif userChoice == "Scissors":
    if computerChoice == "Rock":
        result = "Computer Won!"
    elif computerChoice == "Paper":
        result = "You Won!"

print(result)